-- MySQL Script generated by MySQL Workbench
-- Thu Mar 19 10:08:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`level_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`level_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`level_user` (
  `level_user` INT NOT NULL AUTO_INCREMENT,
  `level_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`level_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_lastname` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `user_password` VARCHAR(100) NOT NULL,
  `user_cover` VARCHAR(255) NOT NULL,
  `user_create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_lastupdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_status` ENUM('1', '0') NOT NULL DEFAULT '1',
  `level_user` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_level_user1_idx` (`level_user` ASC) ,
  CONSTRAINT `fk_user_level_user1`
    FOREIGN KEY (`level_user`)
    REFERENCES `mydb`.`level_user` (`level_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_description` VARCHAR(255) NOT NULL,
  `product_cover` VARCHAR(255) NOT NULL DEFAULT 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTI_oJIo9RYIzr9rJoLKu3dupulCAyNNSCQeuKlMtH0K802Nru4',
  `product_create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `product_lastupdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `product_like` INT NOT NULL DEFAULT '0',
  `product_video` VARCHAR(255) NULL,
  `product_url` VARCHAR(255) NOT NULL,
  `product_seo_description` VARCHAR(155) NOT NULL,
  `product_seo_tags` VARCHAR(45) NOT NULL,
  `product_status` ENUM('1', '0') NOT NULL DEFAULT '1',
  `user_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_product_user1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_product_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_achives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_achives` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_achives` (
  `id_prodarchive` INT NOT NULL AUTO_INCREMENT,
  `prodarchives_link` VARCHAR(255) NOT NULL,
  `prodarchives_name` VARCHAR(45) NOT NULL DEFAULT 'Catálogo PDF',
  `prodarchives_size` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_prodarchive`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  `category_cover` VARCHAR(255) NOT NULL DEFAULT 'https://www.treadproductions.net/wp-content/themes/Tread-v1.3/images/shop/noimage.jpg',
  `category_status` ENUM('1', '0') NULL DEFAULT '1',
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_has_archives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_has_archives` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_has_archives` (
  `product_achives_id_prodarchive` INT NOT NULL,
  `product_product_id` INT NOT NULL,
  PRIMARY KEY (`product_achives_id_prodarchive`, `product_product_id`),
  INDEX `fk_product_achives_has_product_product1_idx` (`product_product_id` ASC) ,
  INDEX `fk_product_achives_has_product_product_achives_idx` (`product_achives_id_prodarchive` ASC) ,
  CONSTRAINT `fk_product_achives_has_product_product_achives`
    FOREIGN KEY (`product_achives_id_prodarchive`)
    REFERENCES `mydb`.`product_achives` (`id_prodarchive`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_achives_has_product_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_has_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_has_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_has_category` (
  `product_category_category_id` INT NOT NULL,
  `product_product_id` INT NOT NULL,
  PRIMARY KEY (`product_category_category_id`, `product_product_id`),
  INDEX `fk_product_category_has_product_product1_idx` (`product_product_id` ASC) ,
  INDEX `fk_product_category_has_product_product_category1_idx` (`product_category_category_id` ASC) ,
  CONSTRAINT `fk_product_category_has_product_product_category1`
    FOREIGN KEY (`product_category_category_id`)
    REFERENCES `mydb`.`product_category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category_has_product_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tutorial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tutorial` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tutorial` (
  `tutorial_id` INT NOT NULL AUTO_INCREMENT,
  `tutorial_title` VARCHAR(60) NOT NULL,
  `tutorial_description` TEXT NOT NULL,
  `tutorial_cover` VARCHAR(255) NOT NULL,
  `tutorial_url` VARCHAR(255) NOT NULL,
  `tutorial_video` TEXT NULL,
  `tutorial_create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tutorial_lastupdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tutorial_like` INT NOT NULL DEFAULT '0',
  `tutorial_status` ENUM('1', '0') NOT NULL DEFAULT '1',
  `tutorial_seo_description` VARCHAR(255) NOT NULL,
  `tutorial_seo_tags` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`tutorial_id`),
  INDEX `fk_tutorial_user1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_tutorial_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tutorial_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tutorial_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tutorial_category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  `category_cover` VARCHAR(255) NOT NULL,
  `category_status` ENUM('1', '0') NOT NULL DEFAULT '1',
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tutorial_archives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tutorial_archives` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tutorial_archives` (
  `archives_id` INT NOT NULL AUTO_INCREMENT,
  `archives_url` VARCHAR(255) NOT NULL,
  `archives_name` VARCHAR(65) NOT NULL,
  `archives_size` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`archives_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tutorial_has_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tutorial_has_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tutorial_has_category` (
  `tutorial_category_category_id` INT NOT NULL,
  `tutorial_tutorial_id` INT NOT NULL,
  PRIMARY KEY (`tutorial_category_category_id`, `tutorial_tutorial_id`),
  INDEX `fk_tutorial_category_has_tutorial_tutorial1_idx` (`tutorial_tutorial_id` ASC) ,
  INDEX `fk_tutorial_category_has_tutorial_tutorial_category1_idx` (`tutorial_category_category_id` ASC) ,
  CONSTRAINT `fk_tutorial_category_has_tutorial_tutorial_category1`
    FOREIGN KEY (`tutorial_category_category_id`)
    REFERENCES `mydb`.`tutorial_category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tutorial_category_has_tutorial_tutorial1`
    FOREIGN KEY (`tutorial_tutorial_id`)
    REFERENCES `mydb`.`tutorial` (`tutorial_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tutorial_has_archives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tutorial_has_archives` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tutorial_has_archives` (
  `tutorial_archives_archives_id` INT NOT NULL,
  `tutorial_tutorial_id` INT NOT NULL,
  PRIMARY KEY (`tutorial_archives_archives_id`, `tutorial_tutorial_id`),
  INDEX `fk_tutorial_archives_has_tutorial_tutorial1_idx` (`tutorial_tutorial_id` ASC) ,
  INDEX `fk_tutorial_archives_has_tutorial_tutorial_archives1_idx` (`tutorial_archives_archives_id` ASC) ,
  CONSTRAINT `fk_tutorial_archives_has_tutorial_tutorial_archives1`
    FOREIGN KEY (`tutorial_archives_archives_id`)
    REFERENCES `mydb`.`tutorial_archives` (`archives_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tutorial_archives_has_tutorial_tutorial1`
    FOREIGN KEY (`tutorial_tutorial_id`)
    REFERENCES `mydb`.`tutorial` (`tutorial_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`events` ;

CREATE TABLE IF NOT EXISTS `mydb`.`events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `event_title` VARCHAR(45) NOT NULL,
  `event_description` VARCHAR(150) NOT NULL,
  `event_date` TIMESTAMP NOT NULL,
  `event_url` VARCHAR(255) NOT NULL,
  `event_cover` VARCHAR(255) NOT NULL,
  `event_branch` ENUM('1', '0') NOT NULL DEFAULT '0',
  `event_status` ENUM('1', '0') NOT NULL DEFAULT '1',
  `event_tag` VARCHAR(20) NOT NULL,
  `event_photos` LONGTEXT NULL,
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`newsletter_body`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`newsletter_body` ;

CREATE TABLE IF NOT EXISTS `mydb`.`newsletter_body` (
  `newsletter_id` INT NOT NULL AUTO_INCREMENT,
  `newsletter_title` VARCHAR(45) NOT NULL,
  `newsletter_content` LONGTEXT NOT NULL,
  `newsletter_create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `newsletter_lastupdate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`newsletter_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`newsletter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`newsletter` ;

CREATE TABLE IF NOT EXISTS `mydb`.`newsletter` (
  `newsletter_id` INT NOT NULL AUTO_INCREMENT,
  `newsletter_name` VARCHAR(45) NOT NULL DEFAULT 'Visitante',
  `newsletter_email` VARCHAR(255) NOT NULL,
  `newsletter_phone` VARCHAR(18) NULL,
  `newsletter_tag` VARCHAR(45) NULL,
  `newsletter_comment` VARCHAR(255) NULL,
  PRIMARY KEY (`newsletter_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`videos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`videos` (
  `videos_id` INT NOT NULL AUTO_INCREMENT,
  `videos_code` VARCHAR(45) NOT NULL,
  `videos_title` VARCHAR(45) NOT NULL,
  `videos_tag` ENUM('tutorial', 'dicas') NOT NULL,
  PRIMARY KEY (`videos_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
